### ISSUE TITLE
class label

### ISSUE THREAD

**Issue by ervinyo** [sakibuchchash/BSVSO-Dataset#1]
Thank you for share your dataset. I have question about your dataset, How many class label in your dataset ? because I see inside you just have one label.
please reply me

**Comment by sakibuchchash** [comment]
Hello ervinyo,
It is a pleasure to have you interested in our dataset. Yes actually our purpose was to make a dataset that can be used for detecting signboards in images automatically, the image contains billboards, banners also. But to detect the signboards perfectly and accurately we only labelled the signboards and that's why there is only one class label.

**Comment by ervinyo** [comment]
> Hello ervinyo,
> It is a pleasure to have you interested in our dataset. Yes actually our purpose was to make a dataset that can be used for detecting signboards in images automatically, the image contains billboards, banners also. But to detect the signboards perfectly and accurately we only labelled the signboards and that's why there is only one class label.

Oh I see. Thank you
